### Registration user
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "email": "testuser@example.com",
    "username": "testuser",
    "password": "testpass123",
    "password_confirm": "testpass123",
    "type": "buyer"
}

### Autorization user
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "testpass123"
}

### Product list
GET http://127.0.0.1:8000/api/products/
Authorization: Token YOUR_TOKEN_HERE

### Products (filter shop)
GET http://127.0.0.1:8000/api/products/?shop__name=Связной
Authorization: Token YOUR_TOKEN_HERE

### Products (search name)
GET http://127.0.0.1:8000/api/products/?search=iPhone
Authorization: Token YOUR_TOKEN_HERE

### Add product in cart
POST http://127.0.0.1:8000/api/cart/add/
Authorization: Token YOUR_TOKEN_HERE
Content-Type: application/json

{
    "product_info_id": 1,
    "quantity": 1
}

### Remove item from cart
DELETE http://127.0.0.1:8000/api/cart/remove/2/
Authorization: Token YOUR_TOKEN_HERE

### View cart
GET http://127.0.0.1:8000/api/cart/
Authorization: Token YOUR_TOKEN_HERE

### Create contact
POST http://127.0.0.1:8000/api/contacts/
Authorization: Token YOUR_TOKEN_HERE
Content-Type: application/json

{
    "city": "Москва",
    "street": "Тверская",
    "house": "1",
    "phone": "+7 999 123-45-67"
}

### Delete contact
DELETE http://127.0.0.1:8000/api/contacts/1/
Authorization: Token YOUR_TOKEN_HERE

### Confirm order
POST http://127.0.0.1:8000/api/orders/confirm/
Authorization: Token YOUR_TOKEN_HERE
Content-Type: application/json

{
    "contact_id": 1
}

### Get orders
GET http://127.0.0.1:8000/api/orders/
Authorization: Token YOUR_TOKEN_HERE

### Get order details
GET http://127.0.0.1:8000/api/orders/1/
Authorization: Token YOUR_TOKEN_HERE