# Generated by Django 5.2.14 on 2026-06-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='name',
        ),
    ]
